const ALPHABETS = [
  "0-9",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

const STOCK_DATA = [
  {
    name: "Apple Inc",
    value: "100.00",
    lowValue: "30",
    highValue: "32",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
    autoRefresh: true,
    options: [],
  },
  {
    name: "Apple Inc",
    value: "100.00",
    lowValue: "30",
    highValue: "32",
    isUp: false,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
    autoRefresh: false,
    options: ["Contributer", "Live Analytics", "Futures", "Options"],
  },
  {
    name: "Apple Inc",
    value: "100.00",
    lowValue: "30",
    highValue: "32",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
    autoRefresh: false,
    options: ["contributer", "subscriber"],
  },
];

const STOCK_WATCHLIST = [
  {
    name: "Apple Inc",
    volume: "100.00",
    value: "30",
    isUp: false,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
  },
  {
    name: "Apple Inc",
    volume: "100.00",
    value: "30",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
  },
  {
    name: "Apple Inc",
    volume: "100.00",
    value: "30",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
  },
  {
    name: "Apple Inc",
    volume: "100.00",
    value: "30",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
  },
  {
    name: "Apple Inc",
    volume: "100.00",
    value: "30",
    isUp: true,
    valueGain: "+2.00",
    valueGainPercentage: "+2.00%",
  },
];

export { ALPHABETS, STOCK_DATA, STOCK_WATCHLIST };
